#!/usr/bin/env python3
import subprocess
import sys
import re
from collections import defaultdict

def run_nm(nm_path, obj_path):
    result = subprocess.run(
        [nm_path, obj_path],
        capture_output=True, text=True, check=True
    )
    symbols = []
    for line in result.stdout.splitlines():
        parts = line.strip().split()
        if len(parts) == 3:
            symbols.append((parts[0], parts[1], parts[2]))
        elif len(parts) == 2:
            symbols.append(("", parts[0], parts[1]))
    return symbols

def extract_initcalls(symbols):
    initcalls = defaultdict(list)
    con_initcalls = []

    for addr, typ, name in symbols:
        if not name.startswith("__initcall__kmod_"):
            continue
        
        # Filter problematic subsystems based on previous crashes
        if any(x in name for x in ["io_uring", "sysctl", "tty", "pty", "vt"]):
            if not "lkl_console" in name:
                continue

        if name.endswith("con"):
            con_initcalls.append((addr, name))
            continue

        if name.endswith("rootfs"):
            initcalls["rootfs"].append((addr, name))
            continue

        if name.endswith("early") or name.rstrip('s').endswith("early"):
            initcalls["early"].append((addr, name))
            continue

        stripped = name.rstrip('s')
        last = stripped[-1]
        if last.isdigit() and int(last) <= 7:
            initcalls[last].append((addr, name))
        else:
            print(f"WARNING: Unknown level for {name}", file=sys.stderr)

    return initcalls, con_initcalls

def generate_c(initcalls, con_initcalls, symbols, output_path):
    level_order = ['early', '0', '1', '2', '3', '4', '5', 'rootfs', '6', '7']

    lines = []
    lines.append("// AUTO-GENERATED by extract_initcalls.py — DO NOT EDIT")
    lines.append("#include <stdio.h>")
    lines.append("typedef int (*initcall_t)(void);")
    lines.append("")

    all_data_syms = []
    for level in level_order:
        entries = initcalls.get(level, [])
        entries.sort(key=lambda x: x[0])
        for addr, name in entries:
            all_data_syms.append((level, name))
            lines.append(f"extern initcall_t {name};")
    
    for addr, name in con_initcalls:
        lines.append(f"extern initcall_t {name};")
    lines.append("")

    lines.append(f"initcall_t __initcall_table[{max(1, len(all_data_syms))}] = {{0}};")
    lines.append(f"int __initcall_table_size = {len(all_data_syms)};")
    lines.append(f"initcall_t __con_initcall_table[{max(1, len(con_initcalls))}] = {{0}};")
    lines.append(f"int __con_initcall_table_size = {len(con_initcalls)};")
    lines.append("")

    lines.append("void __attribute__((constructor)) init_initcall_tables(void) {")
    for i, (level, name) in enumerate(all_data_syms):
        lines.append(f"    __initcall_table[{i}] = {name};")
            
    if con_initcalls:
        for i, (addr, name) in enumerate(con_initcalls):
            lines.append(f"    __con_initcall_table[{i}] = {name};")

    lines.append("}")
    lines.append("")

    lines.append("// Boundary pointers")
    offset = 0
    lines.append(f"initcall_t *__initcall_start = &__initcall_table[{offset}];")

    for level in level_order:
        entries = initcalls.get(level, [])
        if level == 'early':
            offset += len(entries)
            continue
        sym_name = "rootfs" if level == 'rootfs' else level
        lines.append(f"initcall_t *__initcall{sym_name}_start = &__initcall_table[{offset}];")
        offset += len(entries)

    lines.append(f"initcall_t *__initcall_end = &__initcall_table[{offset}];")
    
    lines.append(f"initcall_t *__con_initcall_start = &__con_initcall_table[0];")
    lines.append(f"initcall_t *__con_initcall_end = &__con_initcall_table[{len(con_initcalls)}];")
    lines.append("")

    lines.append("void *__setup_start[0] = {};")
    lines.append("void *__setup_end[0] = {};")
    lines.append("void *__start___param[0] = {};")
    lines.append("void *__stop___param[0] = {};")
    lines.append("unsigned long long jiffies = 0;")
    lines.append("")

    with open(output_path, "w") as f:
        f.write('\n'.join(lines) + '\n')

    with open("kernel/initcalls.defsym", "w") as f:
        f.write("")

    print(f"Generated {output_path}:")
    total = sum(len(initcalls.get(l, [])) for l in level_order)
    print(f"  {total} initcall entries")

def main():
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <llvm-nm-path> <vmlinux.o> <output.c>")
        sys.exit(1)

    nm_path = sys.argv[1]
    obj_path = sys.argv[2]
    output_path = sys.argv[3]

    symbols = run_nm(nm_path, obj_path)
    initcalls, con_initcalls = extract_initcalls(symbols)
    generate_c(initcalls, con_initcalls, symbols, output_path)

if __name__ == "__main__":
    main()