#!/usr/bin/env bash
# doc-gardening.sh — scan for stale or broken documentation and open fix-up issues.
#
# This script is designed to run in CI (via doc-gardening.yml) or locally.
# It does NOT auto-fix content — it creates a GitHub issue listing problems
# so a human or agent can resolve them.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPORT=""
PROBLEMS=0

add_problem() {
  REPORT="${REPORT}- $1\n"
  PROBLEMS=$((PROBLEMS + 1))
}

NOW=$(date +%s)
STALE_DAYS=180

# ---------- 1. Stale files ----------

echo "Scanning for stale documentation..."

while IFS= read -r mdfile; do
  mod_time=$(stat -c %Y "$mdfile" 2>/dev/null || stat -f %m "$mdfile" 2>/dev/null || echo "$NOW")
  age_days=$(( (NOW - mod_time) / 86400 ))
  if [[ $age_days -gt $STALE_DAYS ]]; then
    rel="${mdfile#"$REPO_ROOT"/}"
    add_problem "**Stale**: \`$rel\` has not been updated in $age_days days."
  fi
done < <(find "$REPO_ROOT/docs" "$REPO_ROOT/AGENTS.md" -name '*.md' -type f 2>/dev/null)

# ---------- 2. Broken cross-links ----------

echo "Scanning for broken cross-links..."

while IFS= read -r mdfile; do
  rel_md="${mdfile#"$REPO_ROOT"/}"
  dir_of_file="$(dirname "$mdfile")"
  while IFS= read -r link; do
    target="${link%%#*}"
    target="${target%%)*}"
    if [[ -z "$target" || "$target" == http* || "$target" == mailto* ]]; then
      continue
    fi
    # Resolve relative to the file's directory
    resolved="$dir_of_file/$target"
    if [[ ! -e "$resolved" ]]; then
      add_problem "**Broken link**: \`$rel_md\` links to \`$target\` which does not exist."
    fi
  done < <(grep -oP '\]\(\K[^)]+' "$mdfile" 2>/dev/null || true)
done < <(find "$REPO_ROOT" -maxdepth 1 -name '*.md' -type f 2>/dev/null; find "$REPO_ROOT/docs" -name '*.md' -type f 2>/dev/null)

# ---------- 3. Orphaned doc files not linked from AGENTS.md ----------

echo "Checking for orphaned docs..."

while IFS= read -r mdfile; do
  rel="${mdfile#"$REPO_ROOT"/}"
  if ! grep -q "$rel" "$REPO_ROOT/AGENTS.md" 2>/dev/null; then
    # Check if it's a sub-doc linked from a parent index
    parent_dir="$(dirname "$mdfile")"
    parent_index="$parent_dir/index.md"
    if [[ -f "$parent_index" ]] && grep -q "$(basename "$mdfile")" "$parent_index" 2>/dev/null; then
      continue  # linked from its own index, which is linked from AGENTS.md
    fi
    add_problem "**Orphaned**: \`$rel\` is not linked from AGENTS.md or a parent index."
  fi
done < <(find "$REPO_ROOT/docs" -name '*.md' -type f 2>/dev/null)

# ---------- 4. Empty files ----------

echo "Checking for empty documentation files..."

while IFS= read -r mdfile; do
  if [[ ! -s "$mdfile" ]]; then
    rel="${mdfile#"$REPO_ROOT"/}"
    add_problem "**Empty**: \`$rel\` is empty."
  fi
done < <(find "$REPO_ROOT/docs" -name '*.md' -type f 2>/dev/null)

# ---------- Report ----------

echo ""
echo "=== Doc Gardening Report ==="
echo "Problems found: $PROBLEMS"

if [[ $PROBLEMS -eq 0 ]]; then
  echo "All documentation is healthy."
  exit 0
fi

echo ""
echo -e "$REPORT"

# If running in GitHub Actions with GH_TOKEN, create an issue
if [[ -n "${GH_TOKEN:-}" ]] && command -v gh &>/dev/null; then
  EXISTING=$(gh issue list --label "doc-gardening" --state open --limit 1 --json number -q '.[0].number' 2>/dev/null || echo "")

  BODY="## Doc Gardening Report

Found **$PROBLEMS** problem(s) that need attention:

$(echo -e "$REPORT")

---
*Generated by \`scripts/doc-gardening.sh\` on $(date -u +%Y-%m-%d).*"

  if [[ -n "$EXISTING" ]]; then
    gh issue comment "$EXISTING" --body "$BODY"
    echo "Updated existing issue #$EXISTING"
  else
    gh issue create \
      --title "Doc gardening: $PROBLEMS problem(s) found" \
      --body "$BODY" \
      --label "doc-gardening,documentation"
    echo "Created new issue."
  fi
else
  echo "(Skipping GitHub issue creation — no GH_TOKEN or gh CLI)"
fi

exit 1
